f = open('demo.txt','r+')
print('File Name: ', f.name)
print('File Mode: ', f.mode)
print('Is Readable: ', f.readable())
print('Is Writable: ', f.writable())
print('Is file closed: ', f.closed)
f.close()
print('Is file closed: ', f.closed)